version: '3'
services:
  app:
    build: .
    container_name: om30-app
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - om30-network
    depends_on:
      - db
      - redis
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
  nginx:
    build: .docker/nginx
    container_name: om30-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - om30-network
    depends_on:
      - app

  db:
    build: ./.docker/postgres
    container_name: om30-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=om30
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - om30-network
  redis:
    image: redis:alpine
    container_name: om30-redis
    networks:
      - om30-network
networks:
  om30-network:
    driver: bridge
